inputs_def:
  - handle: online_url
    description: Input
    json_schema:
      contentMediaType: oomol/var
      type: string
    value: ""
  - handle: file_name
    json_schema:
      contentMediaType: oomol/var
      type: string
  - handle: folder
    json_schema:
      contentMediaType: oomol/var
      type: string
      ui:widget: dir
outputs_def:
  - handle: file_address
    description: Output
    json_schema:
      type: string
icon: ":logos:python:"
ui:
  default_width: 530
executor:
  name: python
  options:
    spawn: false
    entry: main.py
